title: Lukas Mateffy
email: lukas@mateffy.me
description: >
  I am a young Javascript, PHP and WordPress Developer from Germany. I love to create for the web and mobile space. I run a small design studio: Smoolabs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mateffy.me"
twitter_username: capevace
github_username:  capevace

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - public/_js
  - public/_css
  - webpack.mix.js
  - tailwind.config.js
  - README.md
  - package-lock.json
  - mix-manifest.json
  - CNAME

collections:
  posts:
    output: true
    permalink: /post/:path
  projects:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"
